# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.provision "shell", inline: <<-script
      apt update
      apt upgrade -y
    script
  #server
  config.vm.define "server" do |dhcp|
    dhcp.vm.network  "private_network",
     ip: "192.168.56.3", 
     virtualbox__intnet: true
    dhcp.vm.provision "shell", inline: <<-script
      apt install isc-dhcp-server -y
    script
  end
  #client
  config.vm.define "client" do |cl|
    cl.vm.network  "private_network", 
      mac: "4f:1b:0d:b6:93:59",
      auto_config: false, 
      virtualbox__intnet: true
  
  end

end
